version: '3.8'
services:
  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: enock
      POSTGRES_PASSWORD: 123interview
      POSTGRES_DB: dellivbd
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network
      
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4242:4242"
    depends_on:
      - postgres
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - backend
    networks:
      - app-network
      
networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
